// Тестовые данные для демонстрации функциональности корзины
export const demoProducts = [
  {
    id: '1798647',
    name: 'Диван-кровать Скаген бежевого цвета',
    price: 25000,
    image: '/images/products/placeholder.svg',
    color: 'Бежевый',
    material: 'Велюр',
    dimensions: '235х90х155 см',
    rating: 4.5,
    reviews: 420,
  },
  {
    id: '2567894',
    name: 'Кресло Стокгольм серого цвета',
    price: 15000,
    image: '/images/products/placeholder.svg',
    color: 'Серый',
    material: 'Текстиль',
    dimensions: '85х92х88 см',
    rating: 4.8,
    reviews: 320,
  },
  {
    id: '3456721',
    name: 'Стол обеденный Монреаль',
    price: 18500,
    image: '/images/products/placeholder.svg',
    color: 'Дуб',
    material: 'Массив дуба',
    dimensions: '180х90х75 см',
    rating: 4.7,
    reviews: 245,
  },
  {
    id: '4789521',
    name: 'Комод Хельсинки белый',
    price: 12000,
    image: '/images/products/placeholder.svg',
    color: 'Белый',
    material: 'МДФ',
    dimensions: '120х45х80 см',
    rating: 4.2,
    reviews: 178,
  },
]; 